
class Localization:
    def __init__(self, lang='ko'):

        self.lang = lang
        self.translations = self.load_translations()

    def load_translations(self):

        return {
            "ko": {
                "id_pw_change_title": "ID/PW 변경",
                "no_user_info_error": "사용자 정보가 없습니다. 다시 로그인해주세요.",
                "select_change_action": "변경할 항목을 선택하세요",
                "change_id": "ID 변경",
                "change_pw": "비밀번호 변경",
                "next_button": "다음",
                "enter_new_value": "새로 사용할 {action}를 입력하세요",
                "save_button": "저장",
                "id_change_success": "ID가 성공적으로 변경되었습니다. 로그아웃 후 첫 페이지로 이동합니다.",
                "pw_change_success": "비밀번호가 성공적으로 변경되었습니다. 로그아웃 후 첫 페이지로 이동합니다.",
                "login_page_title": "로그인 페이지",
                "user_id_input": "아이디",
                "password_input": "비밀번호",
                "login_button": "로그인",
                "login_error_empty": "아이디와 비밀번호를 입력해 주세요.",
                "login_error_failed": "로그인에 실패했습니다. 아이디 또는 비밀번호를 확인해 주세요.",
                "user_info_load_error": "사용자 정보를 불러오는데 실패했습니다.",
                "back_button": "뒤로가기 ↩️",
                "signup_page_title": "회원가입 페이지",
                "email_input": "이메일",
                "signup_button": "회원가입",
                "signup_error_empty": "모든 필드를 입력해 주세요.",
                "signup_success": "회원가입이 완료되었습니다!",
                "signup_error_failed": "회원가입에 실패하였습니다.",
                "home_title": "맛ZIP",
                "logout_button": "로그아웃",
                "logout_success": "로그아웃 성공",
                "profile_button": "프로필",
                "view_post_button": "게시물 보기",
                "group_button": "그룹 페이지",
                "recommended_posts": "추천 맛집 게시물",
                "find_id_pw_button": "ID/PW 찾기",
                "page_not_found": "페이지 '{page}'을 찾을 수 없습니다.",
                "no_previous_page": "이전 페이지가 없습니다.",
                "upload_post_header": "게시물 등록",
                "post_title_input": "게시물 제목",
                "post_content_input": "게시물 내용",
                "image_file_upload": "이미지 파일",
                "general_file_upload": "일반 파일",
                "category_select": "카테고리",
                "post_register_button": "게시물 등록",
                "post_register_success": "게시물이 등록되었습니다.",
                "user_info_not_found": "사용자 정보를 찾을 수 없습니다.",
                "my_page_header": "내 페이지",
                "friend_management": "친구 관리",
                "my_friend_list_button": "내 친구 리스트",
                "friend_requests_button": "친구 대기",
                "user_manager_page_title": "사용자 관리 페이지",
                "email_input_prompt": "이메일을 입력하세요: ",
                "confirm_button": "확인",
                "password_recovery_email_sent": "비밀번호 복구 메일을 전송했습니다",
                "email_not_registered_warning": "등록되지 않은 이메일입니다.",
                "view_post_header": "게시물 목록",
                "upload_post_button": "글 작성",
                "my_made_groups_expander": "내가 만든 그룹 목록",
                "no_joined_groups": "생성한 그룹이 없습니다.",
                "group_name": "그룹 이름",
                "category": "카테고리",
                "status": "상태",
                "meeting_date": "약속 날짜",
                "meeting_time": "약속 시간",
                "edit_button": "수정",
                "delete_button": "삭제",
                "group_deleted_success": "그룹이 삭제되었습니다.",
                "friend_requests_management": "친구 요청 관리",
                "sent_friend_requests": "내가 보낸 친구 요청",
                "no_sent_requests": "보낸 친구 요청이 없습니다.",
                "received_friend_requests": "다른 사람이 보낸 친구 요청",
                "accept": "수락",
                "reject": "거절",
                "no_received_requests": "받은 친구 요청이 없습니다.",
                "group_page_title": "그룹페이지",
                "create_group_button": "그룹 생성",
                "blocked_list_button": "차단 목록",
                "search_group_button": "그룹 검색",
                "category": "카테고리",
                "status": "상태",
                "meeting_date": "약속 날짜",
                "meeting_time": "약속 시간",
                "members_count": "인원수",
                "not_set": "설정되지 않음",
                "detail_button": "세부 정보",
                "detail_group_page": "그룹 세부 정보",
                "group_block_list_title": "그룹 차단 목록",
                "login_required_error": "로그인이 필요합니다.",
                "no_blocked_groups": "차단된 그룹이 없습니다.",
                "blocked_group_id": "차단된 그룹 ID",
                "unblock_button": "차단 해제",
                "unblock_success": "차단 해제 완료:",
                "unblock_error": "차단 해제 중 오류 발생",
                "group_request_list_title": "그룹 대기 목록",
                "no_requests": "대기 중인 요청이 없습니다.",
                "requester_id": "요청자 ID",
                "approve_request": "승인",
                "request_approved": "요청이 승인되었습니다.",
                "reject_request": "거절",
                "request_rejected": "요청이 거절되었습니다.",
                "group_detail_title": "그룹 세부 정보",
                "no_group_error": "그룹 정보가 없습니다.",
                "group_info_not_found": "그룹 정보를 찾을 수 없습니다.",
                "current_members": "현재 인원수",
                "last_modified": "마지막 수정일",
                "meeting_date": "약속 날짜",
                "meeting_time": "약속 시간",
                "not_set": "설정되지 않음",
                "group_members": "그룹원",
                "no_members_in_group": "이 그룹에 소속된 멤버가 없습니다.",
                "block_group": "그룹 차단",
                "unblock_group": "차단 해제",
                "group_blocked_success": "그룹이 차단되었습니다.",
                "group_blocked_error": "차단 중 오류가 발생했습니다.",
                "group_unblocked_success": "차단이 해제되었습니다.",
                "group_unblocked_error": "해제 중 오류가 발생했습니다.",
                "invite_to_group": "그룹 초대",
                "enter_invitee_id": "초대할 사용자 ID를 입력하세요",
                "group_id_not_found_error":"그룹 ID를 찾을 수 없습니다.",
                "send_invite": "초대 요청 보내기",
                "invite_sent_success": "님에게 초대 요청을 보냈습니다.",
                "group_invite_confirmed": "그룹 초대가 되었습니다.",
                "invite_failed": "초대 요청을 보내는 데 실패했습니다.",
                "enter_valid_invitee_id": "초대할 사용자 ID를 입력하세요.",
                "group_block_list_title": "그룹 차단 목록",
                "login_required": "로그인이 필요합니다.",
                "no_blocked_groups": "차단된 그룹이 없습니다.",
                "blocked_group_id": "차단된 그룹 ID",
                "unblock": "차단 해제",
                "group_unblocked_success": "차단 해제 성공",
                "group_unblock_error": "차단 해제 실패",
                "create_group_dialog_title": "그룹 생성",
                "create_group_header": "그룹 생성",
                "group_name_label": "그룹 이름",
                "group_name_placeholder": "그룹 이름을 입력하세요",
                "max_members_label": "최대 인원 수",
                "select_meeting_date_label": "약속 날짜 선택",
                "select_meeting_time_label": "약속 시간 선택",
                "create_group_button": "그룹 생성",
                "update_group_dialog_title": "그룹 수정",
                "update_group_header": "그룹을 수정합니다.",
                "meeting_date_label": "약속 날짜",
                "meeting_time_label": "약속 시간",
                "group_status_label": "그룹 상태",
                "status_in_progress": "진행 중",
                "status_completed": "완료",
                "status_canceled": "취소",
                "update_group_button": "그룹 수정",
                "search_group_dialog_title": "그룹 검색",
                "search_group_header": "그룹 검색 및 참여",
                "search_criteria_label": "검색 기준을 선택하세요",
                "search_by_name": "이름",
                "search_by_date": "날짜",
                "search_by_category": "카테고리",
                "group_name_prompt": "그룹 이름을 입력하세요",
                "meeting_date_prompt": "약속 날짜를 선택하세요",
                "search_button_label": "검색",
                "no_search_results": "검색 결과가 없습니다.",
                "group_name": "그룹 이름",
                "group_leader": "그룹장",
                "current_members": "현재 인원수",
                "meeting_date": "약속 날짜",
                "meeting_time": "약속 시간",
                "category": "카테고리",
                "location": "장소",
                "join_group": "그룹 참여",
                "friend_request_input_label": "친구 요청을 보낼 ID를 입력하세요:",
                "friend_request_button": "친구 요청",
                "friend_request_warning": "친구 요청할 ID를 입력해주세요.",
                "unblock_friend_dialog_title": "친구 차단 해제 창",
                "unblock_friend_input_label": "차단 해제할 친구의 ID를 입력하세요:",
                "unblock_friend_button": "차단 해제",
                "unblock_friend_warning": "친구 차단 해제할 ID를 입력해주세요.",
                "blocked_list_title": "차단된 친구 목록",
                "blocked_users_subheader": "현재 차단된 사용자:",
                "no_blocked_users": "차단된 사용자가 없습니다.",
                "no_friend_id_error": "친구 ID가 없습니다.",
                "friend_posts_title": "{friend_id}님의 포스팅",
                "no_image_message": "이미지가 없습니다.",
                "no_posts_warning": "작성한 포스팅이 없습니다.",
                "db_error": "데이터베이스 오류: {error}",
                "delete_friend_dialog_title": "친구 삭제 창",
                "delete_friend_input_label": "삭제할 친구의 ID를 입력하세요:",
                "delete_friend_button": "친구 삭제",
                "delete_friend_warning": "삭제할 친구의 ID를 입력해주세요.",
                "block_friend_dialog_title": "친구 차단 창",
                "block_friend_input_label": "차단할 친구의 ID를 입력하세요:",
                "block_friend_button": "친구 차단",
                "block_friend_warning": "친구 차단할 ID를 입력해주세요.",
                "friend_requests_dialog_title": "친구 대기 창",
                "friend_list_title": "내 친구 리스트",
                "send_friend_request_button": "친구 요청",
                "password_length_error": "비밀번호는 최소 8자 이상이어야 합니다.",
                "password_change_success": "비밀번호가 변경되었습니다.",
                "password_minimum_length": "비밀번호는 8자리 이상이어야 합니다.",
                "user_id_exists_error": "이미 사용 중인 아이디입니다.",
                "login_success": "{user_id}님, 로그인 성공!",
                "password_incorrect_error": "비밀번호가 틀렸습니다.",
                "user_id_not_found_error": "아이디가 존재하지 않습니다.",
                "no_search_results": "검색 결과가 없습니다.",
                "api_request_error": "API 요청 오류: {status_code}",
                "search_location_input": "검색할 장소를 입력하세요:",
                "search_button": "검색",
                "select_search_result": "검색 결과를 선택하세요:",
                "place_name": "장소 이름",
                "address": "주소",
                "password_recovery_subject": "비밀번호 복구 토큰",
                "password_recovery_body": "안녕하세요,\n\n비밀번호 복구 요청이 접수되었습니다. 아래의 복구 토큰을 사용하세요:\n\n{token}\n\n이 요청을 본인이 하지 않은 경우, 이 이메일을 무시해 주세요.",
                "email_sent_success": "복구 이메일이 {email}으로 성공적으로 전송되었습니다.",
                "email_failed_smtp": "SMTP 오류로 인해 이메일 전송 실패: {error}",
                "email_failed_generic": "예기치 않은 오류로 인해 이메일 전송 실패: {error}",
                "invalid_token": "유효하지 않은 토큰입니다.",
                "password_reset_success": "비밀번호가 성공적으로 복구되었습니다.",
                "user_not_found": "사용자 ID '{user_id}'를 찾을 수 없습니다.",
                "missing_required_fields": "모든 필수 입력 항목을 입력해주세요.",
                "status_in_progress": "진행 중",
                "group_creation_success": "'{group_name}' 그룹이 성공적으로 생성되었습니다!",
                "no_posts_found": "사용자 ID '{user_id}'로 작성된 게시물이 없습니다.",
                "post_retrieval_error": "게시물 조회 중 오류가 발생했습니다: {error}",
                "like_removed": "좋아요를 취소했습니다.",
                "like_added": "좋아요를 추가했습니다!",
                "total_likes": "총 좋아요 수: {total_likes}",
                "unlike_button": "좋아요 취소",
                "like_button": "좋아요",
                "no_locations_found": "위치가 존재하지 않습니다",
                "location_name": "장소 이름: {name}",
                "location_address": "주소: {address}",
                "no_location_data": "위치 데이터가 없습니다.",
                "edit_post_title_label": "게시물 제목",
                "edit_post_content_label": "게시물 내용",
                "edit_post_image_upload": "이미지 파일",
                "edit_post_file_upload": "일반 파일",
                "edit_post_category_label": "카테고리",
                "edit_post_submit_button": "게시물 수정",
                "edit_post_success_message": "게시물이 수정되었습니다.",
                "edit_post_not_found_error": "해당 게시물이 존재하지 않습니다.",
                "post_id_and_title": "게시물 ID: {post_id}, 제목: {title}",
                "post_content": "내용: {content}",
                "delete_post_button": "삭제",
                "delete_post_success_message": "게시물 '{title}'가 삭제되었습니다.",
                "edit_post_expander": "수정",
                "location_map_title": "위치 지도",
                "post_dates": "**등록 날짜**: {upload_date}, **수정 날짜**: {modify_date}",
                "sort_posts_label": "정렬 방식",
                "sort_by_latest": "최신순",
                "sort_by_popularity": "인기순",
                "no_recommended_posts_message": "현재 추천 포스팅이 없습니다.",
                "view_more_expander": "더보기",
                "select_category_label": "카테고리 선택",
                "no_registered_categories_error": "등록된 카테고리가 없습니다. 관리자에게 문의하세요.",
                "dark_mode_button_label": "어두운 모드 🌜",
                "light_mode_button_label": "밝은 모드 🌞",
                "user_email": "사용자 이메일: {email}",
                "user_info_not_found": "사용자 정보를 찾을 수 없습니다.",
                "change_profile_picture": "프로필 사진 변경",
                "upload_new_profile_picture": "새 프로필 사진 업로드",
                "upload_button": "업로드",
                "profile_picture_updated": "프로필 사진이 성공적으로 업데이트되었습니다.",
                "file_save_failed": "파일 저장에 실패했습니다.",
                "field_updated": "{field}이(가) 성공적으로 업데이트되었습니다.",
                "user_info_fetch_failed": "업데이트 후 사용자 정보를 가져오는 데 실패했습니다.",
                "field_update_failed": "사용자 정보를 업데이트하는 데 실패했습니다.",
                "alarm_settings": "알람 설정",
                "alarm_enabled": "알람이 설정되었습니다.",
                "alarm_disabled": "알람이 해제되었습니다.",
                "edit_my_info": "내 정보 수정하기",
                "new_email": "새 이메일 주소",
                "change_email_button": "이메일 변경",
                "new_password": "새 비밀번호",
                "change_password_button": "비밀번호 변경",
                "profile_picture_changed": "프로필 사진이 변경되었습니다.",
                "favorites": "관심목록",
                "friend_requests_title": "친구 대기 창",
                "message_saved": "{sender}님의 메세지가 저장되었습니다.",
                "group_not_found": "그룹이 존재하지 않습니다.",
                "chat_title": "채팅: {group}",
                "login_required": "로그인이 필요합니다.",
                "chat_history": "### 채팅 기록",
                "message_input": "메시지 입력",
                "send_button": "보내기",
                "message_required": "메시지를 입력해주세요.",
                "group_member_added_success": "그룹 멤버가 성공적으로 추가되었습니다!",
                "group_member_add_error": "멤버 추가 중 오류 발생: {error}",
                "group_details": "그룹: {group_name}",
                "group_not_found": "그룹을 찾을 수 없습니다.",
                "group_deleted_success": "그룹이 성공적으로 삭제되었습니다!",
                "group_delete_error": "그룹 삭제 중 오류 발생: {error}",
                "group_updated_success": "'{group_name}' 그룹이 성공적으로 수정되었습니다!",
                "db_error": "DB 오류: {error}",
                "already_member": "이미 해당 그룹의 멤버입니다.",
                "group_joined_success": "'{group_name}' 그룹에 성공적으로 참여하였습니다.",
                "group_blocked_success": "그룹이 성공적으로 차단되었습니다!",
                "group_block_error": "그룹 차단 중 오류 발생: {error}",
                "group_unblocked_success": "그룹 차단이 성공적으로 해제되었습니다!",
                "group_not_blocked": "차단된 그룹이 존재하지 않습니다.",
                "group_unblock_error": "그룹 차단 해제 중 오류 발생: {error}",
                "blocked_groups_error": "차단된 그룹 조회 중 오류 발생: {error}",
                "is_group_blocked_error": "그룹 차단 여부 확인 중 오류 발생: {error}",
                "search_by_name": "이름으로 검색",
                "search_by_date": "날짜로 검색",
                "search_by_category": "카테고리로 검색",
                "friend_list_title": "내 친구 리스트",
                "no_friends": "친구가 없습니다.",
                "blocked_list_title": "차단 목록",
                "no_blocked_users": "차단된 사용자가 없습니다.",
                "block_self_error": "자신을 차단할 수 없습니다.",
                "user_not_found": "없는 ID입니다.",
                "already_blocked": "이미 차단된 사용자입니다.",
                "block_success": "{friend_id}님을 차단하였습니다.",
                "not_blocked_user": "차단된 사용자가 아닙니다.",
                "unblock_success": "{friend_id}님을 차단 해제하였습니다.",
                "delete_self_error": "자신을 삭제할 수 없습니다.",
                "not_in_friend_list": "해당 유저는 내 친구 리스트에 없는 유저입니다.",
                "delete_friend_success": "{friend_id}님을 친구 목록에서 삭제하였습니다.",
                "add_self_as_friend_error": "자신을 친구로 추가할 수 없습니다.",
                "unblock_before_request_error": "먼저 차단을 해제해주세요.",
                "user_id_not_found_error": "없는 ID입니다.",
                "already_friends_error": "이미 친구입니다.",
                "already_requested_error": "이미 친구 요청을 보냈습니다.",
                "debug_my_friend_requests": "내가 보낸 친구 요청:",
                "friend_request_sent_success": "{friend_id}님에게 친구 요청을 보냈습니다. 상대방이 수락할 때까지 기다려주세요.",
                "friend_request_accepted_success": "{requester_id}님과 친구가 되었습니다.",
                "friend_request_rejected_success": "{requester_id}님의 친구 요청을 거절했습니다.",
                "not_in_group": "이 그룹에 소속되어 있지 않습니다.",
                "leave_group_success": "'{group_id}' 그룹에서 성공적으로 탈퇴했습니다.",
                "leave_group_error": "그룹 탈퇴 중 오류 발생: {error}",
                "enter_recovery_token": "복구 토큰",
                "token_placeholder": "이메일로 받은 토큰을 입력하세요",
                "new_password_label": "새 비밀번호",
                "new_password_placeholder": "새 비밀번호를 입력하세요",
                "recover_password_button": "비밀번호 복구",
                "all_fields_required": "모든 필드를 입력하세요.",
                "password_reset_success": "비밀번호가 성공적으로 변경되었습니다!",
                "invalid_or_expired_token": "유효하지 않은 토큰이거나 토큰이 만료되었습니다.",
                "my_groups_expander": "내가 속한 그룹 목록",
                "no_joined_groups": "가입한 그룹이 없습니다.",
                "group_name": "그룹 이름",
                "category": "카테고리",
                "status": "상태",
                "meeting_date": "약속 날짜",
                "meeting_time": "약속 시간",
                "edit_button": "수정",
                "delete_button": "삭제",
                "kick_member_button": "그룹원 내쫓기",
                "kick_member_dialog": "그룹원 내쫓기",
                "group_members_in": "그룹 멤버",
                "no_members": "이 그룹에 멤버가 없습니다.",
                "admin_role": "관리자",
                "member_role": "멤버",
                "kick_button": "내쫓기",
                "kick_success": "{member_id}님을 그룹에서 내쫓았습니다.",
                "kick_error": "{member_id}님을 내쫓는 중 오류가 발생했습니다.",
                "exit_group_dialog": "그룹 나가기",
                "exit_group_confirmation": "정말로 '{group_name}' 그룹을 나가시겠습니까?",
                "yes_button": "예",
                "no_button": "아니요",
                "exit_group_success": "그룹 '{group_name}'을 성공적으로 나갔습니다.",
                "exit_group_cancelled": "그룹 나가기가 취소되었습니다.",
                "delete_group_dialog": "그룹 삭제",
                "delete_group_confirmation": "정말로 '{group_name}' 그룹을 삭제하시겠습니까?",
                "group_deleted": "'{group_name}' 그룹이 삭제되었습니다.",
                "not_group_creator": "그룹 생성자만 삭제할 수 있습니다.",
                "delete_group_cancelled": "그룹 삭제가 취소되었습니다.",
                "my_groups_expander": "내가 속한 그룹 목록",
                "no_joined_groups": "가입한 그룹이 없습니다.",
                "no_maded_groups": "생성된 그룹이 없습니다.",
                "group_name": "그룹 이름",
                "category": "카테고리",
                "status": "상태",
                "meeting_date": "약속 날짜",
                "meeting_time": "약속 시간",
                "chat": "그룹 채팅",
                "enter_chat_button": "채팅 입장하기",
                "leave_group_button": "그룹 탈퇴",
                "choose_language": "언어를 선택해주세요",
                "select_language": "언어 선택"

            },
            "en": {
                "id_pw_change_title": "ID/PW Change",
                "no_user_info_error": "User information not found. Please log in again.",
                "select_change_action": "Select an item to change",
                "change_id": "Change ID",
                "change_pw": "Change Password",
                "next_button": "Next",
                "enter_new_value": "Enter a new {action}",
                "save_button": "Save",
                "id_change_success": "ID has been successfully changed. Logging out and returning to the home page.",
                "pw_change_success": "Password has been successfully changed. Logging out and returning to the home page.",
                "login_page_title": "Login Page",
                "user_id_input": "User ID",
                "password_input": "Password",
                "login_error_empty": "Please enter your user ID and password.",
                "login_error_failed": "Login failed. Please check your user ID and password.",
                "user_info_load_error": "Failed to load user information.",
                "signup_page_title": "Signup Page",
                "email_input": "Email Address",
                "signup_button": "Sign Up",
                "signup_error_empty": "Please fill in all fields.",
                "signup_success": "Sign up completed successfully!",
                "signup_error_failed": "Sign up failed.",
                "logout_button": "Logout",
                "group_id_not_found_error": "Group ID not found.",
                "logout_success": "Logout successful.",
                "profile_button": "Profile",
                "view_post_button": "View Posts",
                "group_button": "Group Page",
                "recommended_posts": "Recommended Posts",
                "home_title": "MatZIP",
                "login_button": "Login",
                "find_id_pw_button": "Find ID/PW",
                "page_not_found": "Page '{page}' not found.",
                "no_previous_page": "No previous page available.",
                "upload_post_header": "Upload Post",
                "post_title_input": "Post Title",
                "post_content_input": "Post Content",
                "image_file_upload": "Image File",
                "general_file_upload": "General File",
                "category_select": "Category",
                "post_register_button": "Register Post",
                "post_register_success": "Post has been registered.",
                "back_button": "Back ↩️",
                "user_info_not_found": "User information could not be found.",
                "my_page_header": "My Page",
                "friend_management": "Friend Management",
                "my_friend_list_button": "My Friend List",
                "friend_requests_button": "Friend Requests",
                "user_manager_page_title": "User Management Page",
                "email_input_prompt": "Enter your email: ",
                "confirm_button": "Confirm",
                "password_recovery_email_sent": "Password recovery email has been sent.",
                "email_not_registered_warning": "The email is not registered.",
                "friend_management": "Friend Management",
                "my_friend_list_button": "My Friend List",
                "friend_requests_button": "Friend Requests",
                "friend_requests_title": "Friend Request Management",
                "user_manager_page_title": "User Management Page",
                "email_input_prompt": "Enter your email",
                "confirm_button": "Confirm",
                "password_recovery_email_sent": "Password recovery email has been sent.",
                "email_not_registered_warning": "The email is not registered.",
                "view_post_header": "Post List",
                "upload_post_button": "Create Post",
                "my_made_groups_expander": "Groups I Created",
                "no_maded_groups": "No groups created",
                "group_name": "Group Name",
                "category": "Category",
                "status": "Status",
                "meeting_date": "Meeting Date",
                "meeting_time": "Meeting Time",
                "edit_button": "Edit",
                "delete_button": "Delete",
                "group_deleted_success": "Group has been deleted.",
                "friend_requests_management": "Friend Request Management",
                "sent_friend_requests": "Friend Requests Sent",
                "no_sent_requests": "No sent friend requests.",
                "received_friend_requests": "Friend Requests Received",
                "accept": "Accept",
                "reject": "Reject",
                "no_received_requests": "No received friend requests.",
                "group_page_title": "Group Page",
                "create_group_button": "Create Group",
                "blocked_list_button": "Blocked List",
                "search_group_button": "Search Groups",
                "friend_requests_title": "Friend Pending Requests",
                "category": "Category",
                "status": "Status",
                "meeting_date": "Meeting Date",
                "meeting_time": "Meeting Time",
                "members_count": "Members Count",
                "not_set": "Not set",
                "detail_button": "Details",
                "detail_group_page": "Group Details",
                "group_block_list_title": "Blocked Groups List",
                "login_required_error": "Login is required.",
                "no_blocked_groups": "No blocked groups found.",
                "blocked_group_id": "Blocked Group ID",
                "unblock_button": "Unblock",
                "unblock_success": "Unblock successful:",
                "unblock_error": "Error occurred while unblocking.",
                "group_request_list_title": "Group Requests",
                "no_requests": "No pending requests.",
                "requester_id": "Requester ID",
                "approve_request": "Approve",
                "request_approved": "Request approved.",
                "reject_request": "Reject",
                "request_rejected": "Request rejected.",
                "group_detail_title": "Group Details",
                "no_group_error": "Group information is not available.",
                "group_info_not_found": "Group information could not be found.",
                "current_members": "Current Members",
                "last_modified": "Last Modified",
                "meeting_date": "Meeting Date",
                "meeting_time": "Meeting Time",
                "not_set": "Not set",
                "group_members": "Group Members",
                "no_members_in_group": "No members in this group.",
                "block_group": "Block Group",
                "unblock_group": "Unblock Group",
                "group_blocked_success": "Group has been blocked.",
                "group_blocked_error": "Error occurred while blocking the group.",
                "group_unblocked_success": "Group has been unblocked.",
                "group_unblocked_error": "Error occurred while unblocking the group.",
                "invite_to_group": "Invite to Group",
                "enter_invitee_id": "Enter the ID of the user to invite",
                "send_invite": "Send Invite Request",
                "invite_sent_success": "has been invited.",
                "group_invite_confirmed": "Group invitation confirmed.",
                "invite_failed": "Failed to send invitation request.",
                "enter_valid_invitee_id": "Please enter a valid ID to invite.",
                "group_block_list_title": "Blocked Groups List",
                "login_required": "Login is required.",
                "no_blocked_groups": "No blocked groups.",
                "blocked_group_id": "Blocked Group ID",
                "unblock": "Unblock",
                "group_unblocked_success": "Unblock successful",
                "group_unblock_error": "Unblock failed",
                "create_group_dialog_title": "Create Group",
                "create_group_header": "Create Group",
                "group_name_label": "Group Name",
                "group_name_placeholder": "Enter group name",
                "max_members_label": "Maximum Members",
                "select_meeting_date_label": "Select Meeting Date",
                "select_meeting_time_label": "Select Meeting Time",
                "create_group_button": "Create Group",
                "update_group_dialog_title": "Update Group",
                "update_group_header": "Update Group",
                "meeting_date_label": "Meeting Date",
                "meeting_time_label": "Meeting Time",
                "group_status_label": "Group Status",
                "status_in_progress": "In Progress",
                "status_completed": "Completed",
                "status_canceled": "Canceled",
                "update_group_button": "Update Group",
                "search_group_dialog_title": "Search Groups",
                "search_group_header": "Search and Join Groups",
                "search_criteria_label": "Select Search Criteria",
                "search_by_name": "Name",
                "search_by_date": "Date",
                "search_by_category": "Category",
                "group_name_prompt": "Enter group name",
                "meeting_date_prompt": "Select meeting date",
                "search_button_label": "Search",
                "no_search_results": "No search results found.",
                "group_name": "Group Name",
                "select_category_label": "Select Category",
                "no_registered_categories_error": "No registered categories found. Please contact the administrator.",
                "group_leader": "Group Leader",
                "current_members": "Current Members",
                "meeting_date": "Meeting Date",
                "meeting_time": "Meeting Time",
                "category": "Category",
                "location": "Location",
                "join_group": "Join Group",
                "friend_request_input_label": "Enter the ID to send a friend request:",
                "friend_request_button": "Send Friend Request",
                "friend_request_warning": "Please enter the ID to send a friend request.",
                "unblock_friend_dialog_title": "Unblock Friend Dialog",
                "unblock_friend_input_label": "Enter the ID to unblock a friend:",
                "unblock_friend_button": "Unblock Friend",
                "unblock_friend_warning": "Please enter the ID to unblock a friend.",
                "blocked_list_title": "Blocked Friends List",
                "blocked_users_subheader": "Currently Blocked Users:",
                "no_blocked_users": "No blocked users found.",
                "no_friend_id_error": "No friend ID found.",
                "friend_posts_title": "{friend_id}'s Posts",
                "no_image_message": "No image available.",
                "no_posts_warning": "No posts available.",
                "db_error": "Database error: {error}",
                "delete_friend_dialog_title": "Delete Friend Dialog",
                "delete_friend_input_label": "Enter the ID to delete a friend:",
                "delete_friend_button": "Delete Friend",
                "delete_friend_warning": "Please enter the ID to delete a friend.",
                "block_friend_dialog_title": "Block Friend Dialog",
                "block_friend_input_label": "Enter the ID to block a friend:",
                "block_friend_button": "Block Friend",
                "block_friend_warning": "Please enter the ID to block a friend.",
                "friend_requests_dialog_title": "Friend Requests Dialog",
                "friend_list_title": "My Friend List",
                "send_friend_request_button": "Send Friend Request",
                "password_length_error": "Password must be at least 8 characters.",
                "user_id_exists_error": "The user ID is already in use.",
                "login_success": "Login successful, welcome {user_id}!",
                "password_incorrect_error": "The password is incorrect.",
                "user_id_not_found_error": "The user ID does not exist.",
                "no_search_results": "No search results found.",
                "api_request_error": "API request error: {status_code}",
                "search_location_input": "Enter a location to search:",
                "search_button": "Search",
                "select_search_result": "Select a search result:",
                "place_name": "Place Name",
                "address": "Address",
                "password_recovery_subject": "Password Recovery Token",
                "password_recovery_body": "Hello,\n\nA password recovery request has been received. Please use the recovery token below:\n\n{token}\n\nIf you did not request this, please ignore this email.",
                "email_sent_success": "Recovery email successfully sent to {email}.",
                "email_failed_smtp": "Failed to send email due to SMTP error: {error}",
                "email_failed_generic": "Failed to send email due to unexpected error: {error}",
                "invalid_token": "Invalid token.",
                "password_reset_success": "Password has been successfully reset.",
                "user_not_found": "User ID '{user_id}' not found.",
                "missing_required_fields": "Please fill in all required fields.",
                "status_in_progress": "In progress",
                "group_creation_success": "Group '{group_name}' has been successfully created!",
                "no_posts_found": "No posts found for user ID '{user_id}'.",
                "post_retrieval_error": "Error occurred while retrieving posts: {error}",
                "like_removed": "Like has been removed.",
                "like_added": "Like has been added!",
                "total_likes": "Total likes: {total_likes}",
                "unlike_button": "Unlike",
                "like_button": "Like",
                "no_locations_found": "No locations found.",
                "location_name": "Location Name: {name}",
                "location_address": "Address: {address}",
                "no_location_data": "No location data available.",
                "edit_post_title_label": "Post Title",
                "edit_post_content_label": "Post Content",
                "edit_post_image_upload": "Image File",
                "edit_post_file_upload": "General File",
                "edit_post_category_label": "Category",
                "edit_post_submit_button": "Edit Post",
                "edit_post_success_message": "Post has been updated.",
                "edit_post_not_found_error": "The post does not exist.",
                "post_id_and_title": "Post ID: {post_id}, Title: {title}",
                "post_content": "Content: {content}",
                "delete_post_button": "Delete",
                "delete_post_success_message": "The post '{title}' has been deleted.",
                "edit_post_expander": "Edit",
                "location_map_title": "Location Map",
                "post_dates": "**Upload Date**: {upload_date}, **Modify Date**: {modify_date}",
                "sort_posts_label": "Sort By",
                "sort_by_latest": "Latest",
                "sort_by_popularity": "Most Popular",
                "no_recommended_posts_message": "There are no recommended posts currently.",
                "view_more_expander": "View More",
                "dark_mode_button_label": "Dark Mode 🌜",
                "light_mode_button_label": "Light Mode 🌞",
                "user_email": "User Email: {email}",
                "user_info_not_found": "User information not found.",
                "change_profile_picture": "Change Profile Picture",
                "upload_new_profile_picture": "Upload New Profile Picture",
                "upload_button": "Upload",
                "profile_picture_updated": "Profile picture successfully updated.",
                "file_save_failed": "Failed to save file.",
                "field_updated": "{field} successfully updated.",
                "user_info_fetch_failed": "Failed to fetch user information after update.",
                "field_update_failed": "Failed to update user information.",
                "alarm_settings": "Alarm Settings",
                "alarm_enabled": "Alarm has been enabled.",
                "alarm_disabled": "Alarm has been disabled.",
                "edit_my_info": "Edit My Info",
                "new_email": "New Email Address",
                "change_email_button": "Change Email",
                "new_password": "New Password",
                "change_password_button": "Change Password",
                "profile_picture_changed": "Profile picture has been changed.",
                "favorites": "Favorites",
                "message_saved": "Message from {sender} has been saved.",
                "password_change_success": "Password has been successfully changed.",
                "password_minimum_length": "Password must be at least 8 characters long.",
                "group_not_found": "Group does not exist.",
                "chat_title": "Chat: {group}",
                "login_required": "Login is required.",
                "chat_history": "### Chat History",
                "message_input": "Enter your message",
                "send_button": "Send",
                "message_required": "Please enter a message.",
                "group_member_added_success": "Group member added successfully!",
                "group_member_add_error": "Error occurred while adding member: {error}",
                "group_details": "Group: {group_name}",
                "group_not_found": "Group not found.",
                "group_deleted_success": "Group deleted successfully!",
                "group_delete_error": "Error occurred while deleting group: {error}",
                "group_updated_success": "Group '{group_name}' updated successfully!",
                "db_error": "Database error: {error}",
                "already_member": "You are already a member of this group.",
                "group_joined_success": "Successfully joined the group '{group_name}'.",
                "group_blocked_success": "The group has been successfully blocked!",
                "group_block_error": "Error occurred while blocking the group: {error}",
                "group_unblocked_success": "The group block has been successfully lifted!",
                "group_not_blocked": "The group is not blocked.",
                "group_unblock_error": "Error occurred while unblocking the group: {error}",
                "blocked_groups_error": "Error occurred while retrieving blocked groups: {error}",
                "is_group_blocked_error": "Error occurred while checking if the group is blocked: {error}",
                "search_by_name": "Search by Name",
                "search_by_date": "Search by Date",
                "search_by_category": "Search by Category",
                "friend_list_title": "My Friend List",
                "no_friends": "No friends found.",
                "blocked_list_title": "Blocked List",
                "no_blocked_users": "No blocked users.",
                "block_self_error": "You cannot block yourself.",
                "user_not_found": "User ID not found.",
                "already_blocked": "This user is already blocked.",
                "block_success": "You have blocked {friend_id}.",
                "not_blocked_user": "This user is not blocked.",
                "unblock_success": "You have unblocked {friend_id}.",
                "delete_self_error": "You cannot delete yourself.",
                "not_in_friend_list": "This user is not in your friend list.",
                "delete_friend_success": "You have removed {friend_id} from your friend list.",
                "add_self_as_friend_error": "You cannot add yourself as a friend.",
                "unblock_before_request_error": "Please unblock the user before sending a request.",
                "user_id_not_found_error": "User ID not found.",
                "already_friends_error": "You are already friends.",
                "already_requested_error": "You have already sent a friend request.",
                "debug_my_friend_requests": "My Friend Requests:",
                "friend_request_sent_success": "You have sent a friend request to {friend_id}. Please wait for their acceptance.",
                "friend_request_accepted_success": "You are now friends with {requester_id}.",
                "friend_request_rejected_success": "You have rejected the friend request from {requester_id}.",
                "not_in_group": "You are not a member of this group.",
                "leave_group_success": "Successfully left the group '{group_id}'.",
                "leave_group_error": "Error occurred while leaving the group: {error}",
                "enter_recovery_token": "Recovery Token",
                "token_placeholder": "Enter the token received via email",
                "new_password_label": "New Password",
                "new_password_placeholder": "Enter your new password",
                "recover_password_button": "Recover Password",
                "all_fields_required": "Please fill in all fields.",
                "password_reset_success": "Your password has been successfully changed!",
                "invalid_or_expired_token": "Invalid or expired token.",
                "my_groups_expander": "My Groups",
                "no_joined_groups": "You have not joined any groups.",
                "group_name": "Group Name",
                "category": "Category",
                "status": "Status",
                "meeting_date": "Meeting Date",
                "meeting_time": "Meeting Time",
                "edit_button": "Edit",
                "delete_button": "Delete",
                "kick_member_button": "Kick Member",
                "kick_member_dialog": "Kick Member",
                "group_members_in": "Group Members in",
                "no_members": "No members in this group.",
                "admin_role": "Admin",
                "member_role": "Member",
                "kick_button": "Kick",
                "kick_success": "Successfully kicked {member_id} from the group.",
                "kick_error": "Error kicking {member_id} from the group.",
                "exit_group_dialog": "Exit Group",
                "exit_group_confirmation": "Do you really want to leave the group '{group_name}'?",
                "yes_button": "Yes",
                "no_button": "No",
                "exit_group_success": "Successfully left the group '{group_name}'.",
                "exit_group_cancelled": "Group exit cancelled.",
                "delete_group_dialog": "Delete Group",
                "delete_group_confirmation": "Do you really want to delete the group '{group_name}'?",
                "group_deleted": "Successfully deleted the group '{group_name}'.",
                "not_group_creator": "Only the group creator can delete this group.",
                "delete_group_cancelled": "Group deletion cancelled.",
                "my_groups_expander": "My Groups",
                "no_joined_groups": "You have not joined any groups.",
                "group_name": "Group Name",
                "category": "Category",
                "status": "Status",
                "chat": "group chat",
                "meeting_date": "Meeting Date",
                "meeting_time": "Meeting Time",
                "enter_chat_button": "Enter Chat",
                "leave_group_button": "Leave Group",
                "choose_language": "please choose language",
                "select_language": "selcet language"

            },
            "jp": {
                "id_pw_change_title": "ID/PW変更",
                "no_user_info_error": "ユーザー情報がありません。もう一度ログインしてください。",
                "select_change_action": "変更する項目を選択してください",
                "change_id": "ID変更",
                "change_pw": "パスワード変更",
                "next_button": "次へ",
                "enter_new_value": "新しい{action}を入力してください",
                "save_button": "保存",
                "id_change_success": "IDが正常に変更されました。ログアウトしてホームページに戻ります。",
                "pw_change_success": "パスワードが正常に変更されました。ログアウトしてホームページに戻ります。",
                "login_page_title": "ログインページ",
                "user_id_input": "ユーザーID",
                "password_input": "パスワード",
                "login_button": "ログイン",
                "login_error_empty": "ユーザーIDとパスワードを入力してください。",
                "login_error_failed": "ログインに失敗しました。ユーザーIDまたはパスワードを確認してください。",
                "user_info_load_error": "ユーザー情報を読み込めませんでした。",
                "back_button": "戻る ↩️",
                "signup_page_title": "サインアップページ",
                "email_input": "メールアドレス",
                "signup_button": "会員登録",
                "signup_error_empty": "すべてのフィールドに入力してください。",
                "signup_success": "サインアップが完了しました！",
                "signup_error_failed": "サインアップに失敗しました。",
                "logout_button": "ログアウト",
                "logout_success": "ログアウトが完了しました。",
                "profile_button": "プロフィール",
                "view_post_button": "投稿を見る",
                "group_button": "グループページ",
                "recommended_posts": "おすすめの投稿",
                "home_title": "味ZIP",
                "find_id_pw_button": "ID/PW 検索",
                "page_not_found": "ページ '{page}' は見つかりません。",
                "no_previous_page": "前のページがありません。",
                "upload_post_header": "投稿の登録",
                "post_title_input": "投稿タイトル",
                "post_content_input": "投稿内容",
                "image_file_upload": "画像ファイル",
                "general_file_upload": "一般ファイル",
                "category_select": "カテゴリー",
                "group_id_not_found_error": "グループIDが見つかりません。",
                "post_register_button":"投稿登録",
                "post_register_success": "投稿が登録されました。",
                "user_info_not_found": "ユーザー情報が見つかりません。",
                "my_page_header": "マイページ",
                "friend_management": "友達管理",
                "my_friend_list_button": "マイフレンドリスト",
                "friend_requests_button": "友達リクエスト",

                "user_manager_page_title": "ユーザー管理ページ",
                "email_input_prompt": "メールアドレスを入力してください: ",
                "confirm_button": "確認",
                "select_category_label": "カテゴリー選択",
                "no_registered_categories_error": "登録されたカテゴリーがありません。管理者にお問い合わせください。",
                "password_recovery_email_sent": "パスワード復旧メールが送信されました",
                "friend_management": "友達管理",
                "my_friend_list_button": "友達リスト",
                "friend_requests_button": "友達リクエスト",
                "friend_requests_title": "友達リクエスト管理",
                "user_manager_page_title": "ユーザー管理ページ",
                "email_input_prompt": "メールアドレスを入力してください",
                "confirm_button": "確認",
                "password_recovery_email_sent": "パスワード復旧メールを送信しました。",
                "email_not_registered_warning": "登録されていないメールアドレスです。",
                "view_post_header": "投稿リスト",
                "upload_post_button": "投稿作成",
                "my_made_groups_expander": "作成したグループ",
                "no_maded_groups": "作成したグループがありません。",
                "group_name": "グループ名",
                "category": "カテゴリー",
                "status": "状態",
                "meeting_date": "予定日",
                "meeting_time": "予定時間",
                "edit_button": "編集",
                "delete_button": "削除",
                "group_deleted_success": "グループが削除されました。",
                "friend_requests_management": "友達リクエスト管理",
                "sent_friend_requests": "送信した友達リクエスト",
                "no_sent_requests": "送信した友達リクエストがありません。",
                "received_friend_requests": "受信した友達リクエスト",
                "accept": "承認",
                "reject": "拒否",
                "no_received_requests": "受信した友達リクエストがありません。",
                "group_page_title": "グループページ",
                "create_group_button": "グループ作成",
                "blocked_list_button": "ブロックリスト",
                "search_group_button": "グループ検索",
                "category": "カテゴリー",
                "status": "状態",
                "meeting_date": "約束日",
                "meeting_time": "約束時間",
                "members_count": "メンバー数",
                "not_set": "設定されていません",
                "detail_button": "詳細",
                "detail_group_page": "グループ詳細",
                "group_block_list_title": "ブロックされたグループリスト",
                "login_required_error": "ログインが必要です。",
                "no_blocked_groups": "ブロックされたグループが見つかりません。",
                "blocked_group_id": "ブロックされたグループ ID",
                "unblock_button": "ブロック解除",
                "unblock_success": "ブロック解除成功:",
                "unblock_error": "ブロック解除中にエラーが発生しました。",
                "group_request_list_title": "グループリクエストリスト",
                "no_requests": "保留中のリクエストはありません。",
                "requester_id": "リクエスター ID",
                "approve_request": "承認",
                "request_approved": "リクエストが承認されました。",
                "reject_request": "拒否",
                "request_rejected": "リクエストが拒否されました。",
                "group_detail_title": "グループ詳細",
                "no_group_error": "グループ情報がありません。",
                "group_info_not_found": "グループ情報が見つかりません。",
                "current_members": "現在のメンバー数",
                "last_modified": "最終更新日",
                "meeting_date": "会議日",
                "meeting_time": "会議時間",
                "friend_requests_title": "友達リクエスト保留",
                "not_set": "設定されていません",
                "group_members": "グループメンバー",
                "no_members_in_group": "このグループにはメンバーがいません。",
                "block_group": "グループをブロック",
                "unblock_group": "ブロックを解除",
                "group_blocked_success": "グループがブロックされました。",
                "group_blocked_error": "グループのブロック中にエラーが発生しました。",
                "group_unblocked_success": "グループのブロックが解除されました。",
                "group_unblocked_error": "ブロック解除中にエラーが発生しました。",
                "invite_to_group": "グループに招待",
                "enter_invitee_id": "招待するユーザーのIDを入力してください",
                "send_invite": "招待リクエストを送信",
                "invite_sent_success": "が招待されました。",
                "group_invite_confirmed": "グループ招待が確認されました。",
                "invite_failed": "招待リクエストの送信に失敗しました。",
                "enter_valid_invitee_id": "招待するユーザーのIDを入力してください",
                "group_block_list_title": "ブロックされたグループ一覧",
                "login_required": "ログインが必要です。",
                "no_blocked_groups": "ブロックされたグループはありません。",
                "blocked_group_id": "ブロックされたグループID",
                "unblock": "ブロック解除",
                "group_unblocked_success": "ブロック解除成功",
                "group_unblock_error": "ブロック解除失敗",
                "create_group_dialog_title": "グループ作成",
                "create_group_header": "グループ作成",
                "group_name_label": "グループ名",
                "group_name_placeholder": "グループ名を入力してください",
                "max_members_label": "最大メンバー数",
                "select_meeting_date_label": "会議の日付を選択",
                "select_meeting_time_label": "会議の時間を選択",
                "create_group_button": "グループ作成",
                "update_group_dialog_title": "グループ編集",
                "update_group_header": "グループ編集",
                "meeting_date_label": "会議の日付",
                "meeting_time_label": "会議の時間",
                "group_status_label": "グループステータス",
                "status_in_progress": "進行中",
                "status_completed": "完了",
                "status_canceled": "キャンセル",
                "update_group_button": "グループ編集",
                "search_group_dialog_title": "グループ検索",
                "search_group_header": "グループを検索して参加",
                "search_criteria_label": "検索基準を選択",
                "password_change_success": "パスワードが変更されました。",
                "password_minimum_length": "パスワードは8文字以上である必要があります。",
                "search_by_name": "名前",
                "search_by_date": "日付",
                "search_by_category": "カテゴリー",
                "group_name_prompt": "グループ名を入力してください",
                "meeting_date_prompt": "会議の日付を選択してください",
                "search_button_label": "検索",
                "no_search_results": "検索結果が見つかりませんでした。",
                "group_name": "グループ名",
                "group_leader": "グループリーダー",
                "current_members": "現在のメンバー数",
                "meeting_date": "会議の日付",
                "meeting_time": "会議の時間",
                "category": "カテゴリー",
                "location": "場所",
                "join_group": "グループ参加",
                "friend_request_input_label": "友達リクエストを送るIDを入力してください:",
                "friend_request_button": "友達リクエストを送る",
                "friend_request_warning": "友達リクエストを送るIDを入力してください。",
                "unblock_friend_dialog_title": "友達のブロック解除ダイアログ",
                "unblock_friend_input_label": "友達のブロック解除するIDを入力してください:",
                "unblock_friend_button": "友達のブロックを解除",
                "unblock_friend_warning": "友達のブロック解除するIDを入力してください。",
                "blocked_list_title": "ブロックされた友達一覧",
                "blocked_users_subheader": "現在ブロックされているユーザー:",
                "no_blocked_users": "ブロックされているユーザーはいません。",
                "no_friend_id_error": "友達IDが見つかりません。",
                "friend_posts_title": "{friend_id}さんの投稿",
                "no_image_message": "画像がありません。",
                "no_posts_warning": "投稿はありません。",
                "db_error": "データベースエラー: {error}",
                "delete_friend_dialog_title": "友達削除ダイアログ",
                "delete_friend_input_label": "友達を削除するIDを入力してください:",
                "delete_friend_button": "友達を削除",
                "delete_friend_warning": "友達を削除するIDを入力してください。",
                "block_friend_dialog_title": "友達をブロックするダイアログ",
                "block_friend_input_label": "友達をブロックするIDを入力してください:",
                "block_friend_button": "友達をブロック",
                "block_friend_warning": "友達をブロックするIDを入力してください。",
                "friend_requests_dialog_title": "友達リクエスト待機ダイアログ",
                "friend_list_title": "私の友達リスト",
                "send_friend_request_button": "友達リクエストを送る",
                "password_length_error": "パスワードは8文字以上である必要があります。",
                "user_id_exists_error": "このユーザーIDは既に使用されています。",
                "login_success": "{user_id}さん、ログイン成功！",
                "password_incorrect_error": "パスワードが間違っています。",
                "user_id_not_found_error": "ユーザーIDが存在しません。",
                "no_search_results": "検索結果がありません。",
                "api_request_error": "APIリクエストエラー: {status_code}",
                "search_location_input": "検索したい場所を入力してください:",
                "search_button": "検索",
                "select_search_result": "検索結果を選択してください:",
                "place_name": "場所名",
                "address": "住所",
                "password_recovery_subject": "パスワード復旧トークン",
                "password_recovery_body": "こんにちは、\n\nパスワードの復旧リクエストを受け付けました。以下の復旧トークンを使用してください：\n\n{token}\n\nこのリクエストを自分で行っていない場合、このメールを無視してください。",
                "email_sent_success": "{email} に復旧メールが正常に送信されました。",
                "email_failed_smtp": "SMTPエラーによりメール送信に失敗しました：{error}",
                "email_failed_generic": "予期しないエラーによりメール送信に失敗しました：{error}",
                "invalid_token": "無効なトークンです。",
                "password_reset_success": "パスワードが正常に復旧されました。",
                "user_not_found": "ユーザーID '{user_id}' が見つかりません。",
                "missing_required_fields": "すべての必須項目を入力してください。",
                "status_in_progress": "進行中",
                "group_creation_success": "「{group_name}」グループが正常に作成されました！",
                "no_posts_found": "ユーザーID「{user_id}」で作成された投稿がありません。",
                "post_retrieval_error": "投稿の取得中にエラーが発生しました: {error}",
                "like_removed": "いいねを取り消しました。",
                "like_added": "いいねを追加しました！",
                "total_likes": "合計いいね数: {total_likes}",
                "unlike_button": "いいね取り消し",
                "like_button": "いいね",
                "no_locations_found": "場所が存在しません。",
                "location_name": "場所の名前: {name}",
                "location_address": "住所: {address}",
                "no_location_data": "位置データがありません。",
                "edit_post_title_label": "投稿のタイトル",
                "edit_post_content_label": "投稿の内容",
                "edit_post_image_upload": "画像ファイル",
                "edit_post_file_upload": "通常ファイル",
                "edit_post_category_label": "カテゴリー",
                "edit_post_submit_button": "投稿を修正する",
                "edit_post_success_message": "投稿が修正されました。",
                "edit_post_not_found_error": "該当する投稿が存在しません。",
                "post_id_and_title": "投稿ID: {post_id}, タイトル: {title}",
                "post_content": "内容: {content}",
                "delete_post_button": "削除",
                "delete_post_success_message": "投稿『{title}』が削除されました。",
                "edit_post_expander": "修正",
                "location_map_title": "位置地図",
                "post_dates": "**登録日**: {upload_date}, **修正日**: {modify_date}",
                "sort_posts_label": "並べ替え方式",
                "sort_by_latest": "最新順",
                "sort_by_popularity": "人気順",
                "no_recommended_posts_message": "現在おすすめの投稿はありません。",
                "view_more_expander": "もっと見る",
                "dark_mode_button_label": "ダークモード 🌜",
                "light_mode_button_label": "ライトモード 🌞",
                "user_email": "ユーザーのメール: {email}",
                "user_info_not_found": "ユーザー情報が見つかりません。",
                "change_profile_picture": "プロフィール写真の変更",
                "upload_new_profile_picture": "新しいプロフィール写真をアップロード",
                "upload_button": "アップロード",
                "profile_picture_updated": "プロフィール写真が正常に更新されました。",
                "file_save_failed": "ファイルの保存に失敗しました。",
                "field_updated": "{field}が正常に更新されました。",
                "user_info_fetch_failed": "更新後のユーザー情報の取得に失敗しました。",
                "field_update_failed": "ユーザー情報の更新に失敗しました。",
                "alarm_settings": "アラーム設定",
                "alarm_enabled": "アラームが設定されました。",
                "alarm_disabled": "アラームが解除されました。",
                "edit_my_info": "自分の情報を編集",
                "new_email": "新しいメールアドレス",
                "change_email_button": "メールアドレスを変更",
                "new_password": "新しいパスワード",
                "change_password_button": "パスワードを変更",
                "profile_picture_changed": "プロフィール写真が変更されました。",
                "favorites": "お気に入り",
                "message_saved": "{sender}さんのメッセージが保存されました。",
                "group_not_found": "グループが存在しません。",
                "chat_title": "チャット: {group}",
                "login_required": "ログインが必要です。",
                "chat_history": "### チャット履歴",
                "message_input": "メッセージを入力してください",
                "send_button": "送信",
                "message_required": "メッセージを入力してください。",
                "group_member_added_success": "グループメンバーが正常に追加されました！",
                "group_member_add_error": "メンバー追加中にエラーが発生しました: {error}",
                "group_details": "グループ: {group_name}",
                "group_not_found": "グループが見つかりません。",
                "group_deleted_success": "グループが正常に削除されました！",
                "group_delete_error": "グループ削除中にエラーが発生しました: {error}",
                "group_updated_success": "'{group_name}' グループが正常に更新されました！",
                "db_error": "データベースエラー: {error}",
                "already_member": "既にこのグループのメンバーです。",
                "group_joined_success": "'{group_name}' グループに正常に参加しました。",
                "group_blocked_success": "グループが正常にブロックされました！",
                "group_block_error": "グループをブロック中にエラーが発生しました: {error}",
                "group_unblocked_success": "グループのブロックが正常に解除されました！",
                "group_not_blocked": "ブロックされたグループは存在しません。",
                "group_unblock_error": "グループのブロック解除中にエラーが発生しました: {error}",
                "blocked_groups_error": "ブロックされたグループの取得中にエラーが発生しました: {error}",
                "is_group_blocked_error": "グループがブロックされているか確認中にエラーが発生しました: {error}",
                "search_by_name": "名前で検索",
                "search_by_date": "日付で検索",
                "search_by_category": "カテゴリーで検索",
                "friend_list_title": "私の友達リスト",
                "no_friends": "友達がいません。",
                "blocked_list_title": "ブロックリスト",
                "no_blocked_users": "ブロックされたユーザーはいません。",
                "block_self_error": "自分自身をブロックすることはできません。",
                "user_not_found": "ユーザーIDが見つかりません。",
                "already_blocked": "このユーザーは既にブロックされています。",
                "block_success": "{friend_id}をブロックしました。",
                "not_blocked_user": "このユーザーはブロックされていません。",
                "unblock_success": "{friend_id}のブロックを解除しました。",
                "delete_self_error": "自分自身を削除することはできません。",
                "not_in_friend_list": "このユーザーは友達リストにいません。",
                "delete_friend_success": "{friend_id}を友達リストから削除しました。",
                "add_self_as_friend_error": "自分を友達に追加することはできません。",
                "unblock_before_request_error": "リクエストを送信する前にブロックを解除してください。",
                "user_id_not_found_error": "ユーザーIDが見つかりません。",
                "already_friends_error": "既に友達です。",
                "already_requested_error": "既に友達リクエストを送信しました。",
                "debug_my_friend_requests": "送信した友達リクエスト：",
                "friend_request_sent_success": "{friend_id}に友達リクエストを送りました。承認をお待ちください。",
                "friend_request_accepted_success": "{requester_id}と友達になりました。",
                "friend_request_rejected_success": "{requester_id}からの友達リクエストを拒否しました。",
                "enter_recovery_token": "復旧トークン",
                "token_placeholder": "メールで受け取ったトークンを入力してください",
                "new_password_label": "新しいパスワード",
                "new_password_placeholder": "新しいパスワードを入力してください",
                "recover_password_button": "パスワードを復旧する",
                "all_fields_required": "すべてのフィールドを入力してください。",
                "password_reset_success": "パスワードが正常に変更されました！",
                "invalid_or_expired_token": "無効または期限切れのトークンです。",
                "not_in_group": "このグループに所属していません。",
                "leave_group_success": "'{group_id}' グループを正常に脱退しました。",
                "leave_group_error": "グループ脱退中にエラーが発生しました: {error}",
                "my_groups_expander": "参加中のグループリスト",
                "no_joined_groups": "参加中のグループはありません。",
                "group_name": "グループ名",
                "category": "カテゴリー",
                "status": "状態",
                "meeting_date": "約束日",
                "meeting_time": "約束時間",
                "enter_chat_button": "チャットに参加",
                "leave_group_button": "グループを脱退",
                "my_groups_expander": "参加中のグループリスト",
                "no_joined_groups": "参加中のグループはありません。",
                "group_name": "グループ名",
                "category": "カテゴリー",
                "status": "状態",
                "meeting_date": "約束日",
                "meeting_time": "約束時間",
                "edit_button": "編集",
                "delete_button": "削除",
                "kick_member_button": "メンバーを追放",
                "kick_member_dialog": "メンバーを追放",
                "group_members_in": "グループのメンバー",
                "no_members": "このグループにはメンバーがいません。",
                "admin_role": "管理者",
                "member_role": "メンバー",
                "kick_button": "追放",
                "kick_success": "{member_id}さんをグループから追放しました。",
                "kick_error": "{member_id}さんを追放中にエラーが発生しました。",
                "exit_group_dialog": "グループを退出",
                "exit_group_confirmation": "本当にグループ「{group_name}」を退出しますか？",
                "yes_button": "はい",
                "no_button": "いいえ",
                "chat": "グループチェチング",
                "exit_group_success": "グループ「{group_name}」を正常に退出しました。",
                "exit_group_cancelled": "グループ退出がキャンセルされました。",
                "delete_group_dialog": "グループを削除",
                "delete_group_confirmation": "本当にグループ「{group_name}」を削除しますか？",
                "group_deleted": "グループ「{group_name}」を正常に削除しました。",
                "not_group_creator": "グループ作成者のみがこのグループを削除できます。",
                "delete_group_cancelled": "グループ削除がキャンセルされました。",
                "choose_language": "言語を選んでください。",
                "select_language": "言語選択"

            }

        }

    def get_text(self, key):

        try:
            return self.translations[self.lang][key]
        except KeyError:
            st.warning(f"'{key}' not found in language '{self.lang}'.")
            return key

    def switch_language(self, new_lang):

        if new_lang in self.translations:
            self.lang = new_lang
        else:
            st.error(f"Language '{new_lang}' is not supported.")

    def show_translations(self):

        st.json(self.translations.get(self.lang, {}))

